version: "3.7"
services:
  overworld:
    build:
      context: https://github.com/dst-academy/docker-dontstarvetogether.git#v0.8.0:build
      args:
        MODS: 347079953,362175979,363112314,374550642,375850593,375859599,378160973,382177939,458587300,458940297,462469447,466732225,623749604,797304209,866623002,885426046
    container_name: dst_overworld
    tty: true
    stdin_open: true
    command: dst-server start --update=all
    env_file: overworld.env
    environment:
      LEVELDATA_OVERRIDES: |
        return {
          desc="The standard Don't Starve experience.",
          hideminimap=false,
          id="SURVIVAL_TOGETHER",
          location="forest",
          max_playlist_position=999,
          min_playlist_position=0,
          name="Default",
          numrandom_set_pieces=4,
          override_level_string=false,
          overrides={
            alternatehunt="default",
            angrybees="default",
            antliontribute="default",
            autumn="longseason",
            bearger="default",
            beefalo="default",
            beefaloheat="default",
            bees="default",
            berrybush="default",
            birds="default",
            boons="default",
            branching="default",
            butterfly="default",
            buzzard="default",
            cactus="default",
            carrot="default",
            catcoon="default",
            chess="default",
            day="default",
            deciduousmonster="default",
            deerclops="default",
            disease_delay="none",
            dragonfly="default",
            flint="default",
            flowers="default",
            frograin="default",
            goosemoose="default",
            grass="default",
            has_ocean=true,
            houndmound="default",
            hounds="default",
            hunt="default",
            keep_disconnected_tiles=true,
            krampus="default",
            layout_mode="LinkNodesByKeys",
            liefs="default",
            lightning="default",
            lightninggoat="default",
            loop="default",
            lureplants="default",
            marshbush="default",
            merm="default",
            meteorshowers="default",
            meteorspawner="default",
            moles="default",
            mushroom="default",
            no_joining_islands=true,
            no_wormholes_to_disconnected_tiles=true,
            penguins="default",
            perd="default",
            petrification="default",
            pigs="default",
            ponds="default",
            prefabswaps_start="default",
            rabbits="default",
            reeds="default",
            regrowth="default",
            roads="default",
            rock="default",
            rock_ice="default",
            sapling="default",
            season_start="default",
            specialevent="default",
            spiders="default",
            spring="default",
            start_location="default",
            summer="default",
            tallbirds="default",
            task_set="default",
            tentacles="default",
            touchstone="default",
            trees="default",
            tumbleweed="default",
            walrus="default",
            weather="default",
            wildfires="never",
            winter="default",
            world_size="default",
            wormhole_prefab="wormhole" 
          },
          random_set_pieces={
            "Sculptures_2",
            "Sculptures_3",
            "Sculptures_4",
            "Sculptures_5",
            "Chessy_1",
            "Chessy_2",
            "Chessy_3",
            "Chessy_4",
            "Chessy_5",
            "Chessy_6",
            "Maxwell1",
            "Maxwell2",
            "Maxwell3",
            "Maxwell4",
            "Maxwell6",
            "Maxwell7",
            "Warzone_1",
            "Warzone_2",
            "Warzone_3" 
          },
          required_prefabs={ "multiplayer_portal" },
          required_setpieces={ "Sculptures_1", "Maxwell5" },
          substitutes={  },
          version=4 
        }
      MODS_OVERRIDES: |
        return {
          ["workshop-347079953"]={
            configuration_options={ DFV_Language="EN", DFV_MinimalMode="default" },
            enabled=true 
          },
          ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
          ["workshop-363112314"]={ configuration_options={  }, enabled=true },
          ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=99 }, enabled=true },
          ["workshop-375850593"]={ configuration_options={  }, enabled=true },
          ["workshop-375859599"]={
            configuration_options={
              divider=5,
              random_health_value=0,
              random_range=0,
              send_unknwon_prefabs=false,
              show_type=0,
              unknwon_prefabs=1,
              use_blacklist=true 
            },
            enabled=true 
          },
          ["workshop-378160973"]={
            configuration_options={
              ENABLEPINGS=true,
              FIREOPTIONS=2,
              OVERRIDEMODE=false,
              SHAREMINIMAPPROGRESS=true,
              SHOWFIREICONS=true,
              SHOWPLAYERICONS=true,
              SHOWPLAYERSOPTIONS=2 
            },
            enabled=true 
          },
          ["workshop-382177939"]={
            configuration_options={ [""]=true, chillit="yep", eightxten="5x16", workit="yep" },
            enabled=true 
          },
          ["workshop-458587300"]={ configuration_options={ Ownership=false, Travel_Cost=32 }, enabled=true },
          ["workshop-458940297"]={
            configuration_options={
              DFV_ClientPrediction="default",
              DFV_FueledSettings="default",
              DFV_Language="EN",
              DFV_MinimalMode="default",
              DFV_PercentReplace="default",
              DFV_ShowACondition="default",
              DFV_ShowADefence="default",
              DFV_ShowAType="default",
              DFV_ShowDamage="default",
              DFV_ShowFireTime="default",
              DFV_ShowInsulation="default",
              DFV_ShowTemperature="default",
              DFV_ShowUses="default" 
            },
            enabled=true 
          },
          ["workshop-462469447"]={ configuration_options={  }, enabled=true },
          ["workshop-466732225"]={ configuration_options={  }, enabled=true },
          ["workshop-623749604"]={
            configuration_options={
              Craft="Normal",
              Destroyable="DestroyByAll",
              FoodSpoilage=1,
              Language="En",
              Position="Center",
              Slots=80 
            },
            enabled=true 
          },
          ["workshop-797304209"]={ configuration_options={  }, enabled=true },
          ["workshop-866623002"]={
            configuration_options={
              _spacer=false,
              alwaysontikitorch=true,
              campfire=true,
              chiminea=true,
              coldfire=true,
              coldfirepit=true,
              deluxe_firepit=true,
              endo_firepit=true,
              firepit=true,
              firepit_obsidian=true,
              flingomaticfuel=false,
              flingomaticrange=2,
              heat_star=true,
              ice_star=true,
              maxwelllight_p=true,
              musha_oven=true,
              nightlight=true,
              obsidianfirepit=true,
              pigtorch=true,
              sea_chiminea=true,
              tungsten_firepit=true 
            },
            enabled=true 
          },
          ["workshop-885426046"]={ configuration_options={  }, enabled=true } 
        }
    ports:
      - "10999:10999/udp"
    volumes:
      - ./overworld:/var/lib/dsta/cluster
  underworld:
    build:
      context: https://github.com/dst-academy/docker-dontstarvetogether.git#v0.8.0:build
      args:
        MODS: 347079953,362175979,363112314,374550642,375850593,375859599,378160973,382177939,458587300,458940297,462469447,466732225,623749604,797304209,866623002,885426046
    container_name: dst_underworld
    tty: true
    stdin_open: true
    command: dst-server start --update=all
    env_file: underworld.env
    environment:
      LEVELDATA_OVERRIDES: |
        return {
          background_node_range={ 0, 1 },
          desc="Delve into the caves... together!",
          hideminimap=false,
          id="DST_CAVE",
          location="cave",
          max_playlist_position=999,
          min_playlist_position=0,
          name="The Caves",
          numrandom_set_pieces=0,
          override_level_string=false,
          overrides={
            banana="default",
            bats="default",
            berrybush="default",
            boons="default",
            branching="default",
            bunnymen="default",
            cave_ponds="default",
            cave_spiders="default",
            cavelight="default",
            chess="default",
            disease_delay="none",
            earthquakes="default",
            fern="default",
            fissure="default",
            flint="default",
            flower_cave="default",
            grass="default",
            layout_mode="RestrictNodesByKey",
            lichen="default",
            liefs="default",
            loop="default",
            marshbush="default",
            monkey="default",
            mushroom="default",
            mushtree="default",
            prefabswaps_start="default",
            reeds="default",
            regrowth="default",
            roads="never",
            rock="default",
            rocky="default",
            sapling="default",
            season_start="default",
            slurper="default",
            slurtles="default",
            start_location="caves",
            task_set="cave_default",
            tentacles="default",
            touchstone="default",
            trees="default",
            weather="default",
            world_size="default",
            wormattacks="default",
            wormhole_prefab="tentacle_pillar",
            wormlights="default",
            worms="default" 
          },
          required_prefabs={ "multiplayer_portal" },
          substitutes={  },
          version=4 
        }
      MODS_OVERRIDES: |
        return {
          ["workshop-347079953"]={
            configuration_options={ DFV_Language="EN", DFV_MinimalMode="default" },
            enabled=true 
          },
          ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
          ["workshop-363112314"]={ configuration_options={  }, enabled=true },
          ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=99 }, enabled=true },
          ["workshop-375850593"]={ configuration_options={  }, enabled=true },
          ["workshop-375859599"]={
            configuration_options={
              divider=5,
              random_health_value=0,
              random_range=0,
              send_unknwon_prefabs=false,
              show_type=0,
              unknwon_prefabs=1,
              use_blacklist=true 
            },
            enabled=true 
          },
          ["workshop-378160973"]={
            configuration_options={
              ENABLEPINGS=true,
              FIREOPTIONS=2,
              OVERRIDEMODE=false,
              SHAREMINIMAPPROGRESS=true,
              SHOWFIREICONS=true,
              SHOWPLAYERICONS=true,
              SHOWPLAYERSOPTIONS=2 
            },
            enabled=true 
          },
          ["workshop-382177939"]={
            configuration_options={ [""]=true, chillit="yep", eightxten="5x16", workit="yep" },
            enabled=true 
          },
          ["workshop-458587300"]={ configuration_options={ Ownership=false, Travel_Cost=32 }, enabled=true },
          ["workshop-458940297"]={
            configuration_options={
              DFV_ClientPrediction="default",
              DFV_FueledSettings="default",
              DFV_Language="EN",
              DFV_MinimalMode="default",
              DFV_PercentReplace="default",
              DFV_ShowACondition="default",
              DFV_ShowADefence="default",
              DFV_ShowAType="default",
              DFV_ShowDamage="default",
              DFV_ShowFireTime="default",
              DFV_ShowInsulation="default",
              DFV_ShowTemperature="default",
              DFV_ShowUses="default" 
            },
            enabled=true 
          },
          ["workshop-462469447"]={ configuration_options={  }, enabled=true },
          ["workshop-466732225"]={ configuration_options={  }, enabled=true },
          ["workshop-623749604"]={
            configuration_options={
              Craft="Normal",
              Destroyable="DestroyByAll",
              FoodSpoilage=1,
              Language="En",
              Position="Center",
              Slots=80 
            },
            enabled=true 
          },
          ["workshop-797304209"]={ configuration_options={  }, enabled=true },
          ["workshop-866623002"]={
            configuration_options={
              _spacer=false,
              alwaysontikitorch=true,
              campfire=true,
              chiminea=true,
              coldfire=true,
              coldfirepit=true,
              deluxe_firepit=true,
              endo_firepit=true,
              firepit=true,
              firepit_obsidian=true,
              flingomaticfuel=false,
              flingomaticrange=2,
              heat_star=true,
              ice_star=true,
              maxwelllight_p=true,
              musha_oven=true,
              nightlight=true,
              obsidianfirepit=true,
              pigtorch=true,
              sea_chiminea=true,
              tungsten_firepit=true 
            },
            enabled=true 
          },
          ["workshop-885426046"]={ configuration_options={  }, enabled=true } 
        }
    ports:
      - "11000:11000/udp"
    volumes:
      - ./underworld:/var/lib/dsta/cluster
